.\"
.\" Copyright 2015 Itay Grudev <itay@grudev.com>
.\"
.\" @(#)imperial.1
.\"
.TH IMPERIAL 1 "April 1, 2015"
.SH NAME
.B imperial
- A proper greet from your computer
.SH SYNOPSIS
.B imperial
(march|start|stop)
.SH DESCRIPTION
.B imperial
is a very sophisticated software that enables your computer to play the Imperial March whenever requested. And the best part - it can play it on boot.
.PP
Heavily relies on the beep utility.
.SH EXAMPLES
.B imperial march
    Starts playing the Imperial March
.PP
.B \imperial stop
    Stops playing the Imperial March
.PP
.B \imperial start
    A more formal way of playing the Imperial March
.SH SEE ALSO
.BR beep (1)
.SH BUGS
Non enlightened people may not understand the significance of this software.
.SH REPORTING BUGS
Report generic bugs to <no-reply@example.com> and severe bugs to <itay@grudev.com>.
.SH AUTHOR
Itay Grudev <itay@grudev.com>
